# Generated by Django 4.0 on 2022-03-20 09:12

from django.db import migrations
import user.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.manager.CustomUserManager()),
            ],
        ),
    ]
